spring:
  profiles:
    active: DEV, PRD
  datasource:
    url: jdbc:postgresql://postgres:lUUYML0lUbeF7yqwJfmF@containers-us-west-61.railway.app:7464/railway
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate